const fs = require('fs');
const path = require('path');
const logger = require('./.agent/utils/logger');

function loadTemplate(templateId) {
    try {
        const tplPath = path.join(__dirname, 'templates', 'layout', `${templateId}.json`);
        const content = fs.readFileSync(tplPath, 'utf8');
        return content;
    } catch (e) {
        logger.error('LayoutComposer', `Failed to load template '${templateId}'`, e);
        return null; // Signals template missing
    }
}

async function createMasterItem(sessionApp, type, id, title, expression) {
    logger.log('LayoutComposer', `Creating Master ${type} '${id}' -> ${expression}`);
    const qInfo = { qId: id, qType: type };

    let props = {};
    if (type === 'measure') {
        props = {
            qInfo,
            qMeasure: { qLabel: title, qDef: expression },
            qMetaDef: { title, description: `Agent generated measure: ${id}` }
        };
        const handle = await sessionApp.createMeasure(props);
        return handle;
    } else if (type === 'dimension') {
        props = {
            qInfo,
            qDim: { qLabel: title, qFieldDefs: [expression] },
            qMetaDef: { title, description: `Agent generated dimension: ${id}` }
        };
        const handle = await sessionApp.createDimension(props);
        return handle;
    }
}

async function injectAndCreateObject(sessionApp, sheetObj, widgetDef) {
    const rawTemplate = loadTemplate(widgetDef.templateId);
    if (!rawTemplate) return null;

    // String Replacement Strategy (JSON Vaccine)
    let injected = rawTemplate
        .replace(/{{MEASURE_1}}/g, widgetDef.masterMeasureId || '')
        .replace(/{{DIMENSION_1}}/g, widgetDef.masterDimensionId || '')
        .replace(/{{TITLE}}/g, widgetDef.title || 'Untitled');

    const jsonProps = JSON.parse(injected);
    const objHandle = await sessionApp.createObject(jsonProps);
    const objLayout = await objHandle.getLayout();

    logger.layout('LayoutComposer', `Created ${widgetDef.templateId} chart: ${objLayout.qInfo.qId}`);
    return {
        id: objLayout.qInfo.qId,
        grid: widgetDef.grid
    };
}

async function composeLayout(sessionApp, layoutPlan) {
    if (!layoutPlan || !layoutPlan.blueprint) {
        logger.error('LayoutComposer', 'Invalid or missing layout plan form LayoutBrain');
        return false;
    }

    try {
        // Step 1: Create Master Items
        logger.log('LayoutComposer', '--- Phase 1: Creating Master Items ---');
        for (const dim of layoutPlan.masterItems?.dimensions || []) {
            await createMasterItem(sessionApp, 'dimension', dim.id, dim.title, dim.expression);
        }
        for (const msr of layoutPlan.masterItems?.measures || []) {
            await createMasterItem(sessionApp, 'measure', msr.id, msr.title, msr.expression);
        }

        // Step 2: Create Base Sheet
        logger.log('LayoutComposer', '--- Phase 2: Creating Executive Dashboard Sheet ---');
        const sheetProps = {
            qInfo: { qType: 'sheet' },
            qMetaDef: { title: 'Executive Dashboard (Agent Generated)', description: 'Auto-generated by Agent 4' },
            cells: []
        };
        const sheetObj = await sessionApp.createObject(sheetProps);
        const sheetLayout = await sheetObj.getLayout();
        const sheetId = sheetLayout.qInfo.qId;
        logger.layout('LayoutComposer', `Base sheet created with ID: ${sheetId}`);

        // Step 3: Inject & Create Charts
        logger.log('LayoutComposer', '--- Phase 3: Building & Mounting Charts ---');
        const createdCells = [];
        for (const widget of layoutPlan.blueprint) {
            const chartData = await injectAndCreateObject(sessionApp, sheetObj, widget);
            if (chartData) {
                // Map the LLM's virtual coordinate grid to Qlik's internal object schema
                createdCells.push({
                    name: chartData.id,
                    type: widget.templateId,
                    col: chartData.grid.x,
                    row: chartData.grid.y,
                    colspan: chartData.grid.width,
                    rowspan: chartData.grid.height
                });
            }
        }

        // Step 4: Mount Charts to Sheet
        const finalSheetProps = await sheetObj.getProperties();
        finalSheetProps.cells = createdCells;
        await sheetObj.setProperties(finalSheetProps);
        logger.layout('LayoutComposer', `Successfully mounted ${createdCells.length} objects to Dashboard.`);

        return true;
    } catch (e) {
        logger.error('LayoutComposer', 'Critical failure during Layout Assembly', e);
        return false;
    }
}

module.exports = { composeLayout };
